# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: GH Security Workflow

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn -B --file pom.xml package dependency:copy-dependencies
        
    - name: Run IQ CLI
      id: evaluate
      uses: sonatype/actions/evaluate@v1.1.0
      with:
        iq-server-url: https://sonatype.sonatype.app/platform
        username: ${{ secrets.SSA_USERNAME }}
        password: ${{ secrets.SSA_PASSWORD }}
        application-id: testdata
        scan-targets: '**/*.jar'
        sarif-file: 'sariffile'
        upload-sarif-file: 'true'

    - name: Fetch SBOM
      uses: sonatype/actions/fetch-sbom@v1
      if: ( success() || failure() ) && steps.evaluate.outputs.scan-id
      with:
        iq-server-url: https://sonatype.sonatype.app/platform
        username: ${{ secrets.IQ_USERNAME }}
        password: ${{ secrets.IQ_PSWRD }}
        application-id: testdata
        scan-id: ${{ steps.evaluate.outputs.scan-id }}
        sbom-standard: spdx
        sbom-version: 2.3
        push-dependency-graph: true
